####################################################################################################
# IBM VSI Controller Logs
####################################################################################################
log:
  level: "INFO"
  console: false
  file: "logs/vsi.log"
  rotation: "10 MB"
  retention: "7 days"
  compression: "zip"
